sudo: required

services:
  - docker

script:
  - docker build -t beevelop/cordova .
  - docker run beevelop/cordova /bin/sh -c "/opt/android/tools/bin/sdkmanager --update && cordova create test && cd test && cordova platform add android && cordova build android"
